#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure Nginx
sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo sed -i 's|root /var/www/html;|root /var/www/html;\n\tindex index.html;|' /etc/nginx/sites-available/default

# Start Nginx
sudo service nginx start
